name: NuGet Generation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/toor1245/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
      
      - name: Build solution and generate NuGet package
        run: |  
          cd src
          dotnet build -c Release -o out
        
      - name: Push generated package to Nuget
        run: |  
          cd src/out
          dotnet nuget push "*.nupkg" -k oy2ieuwry3dxhaqmglhaf7fek7hgtyvepmm3gmtyej25ay -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
